[tasks]
hello = "echo hello from mise"

[tools]
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:anthropics/claude-code" = "latest"
"aqua:aws/aws-cli" = "latest"
"aqua:go-task/task" = "latest"
"aqua:peco/peco" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:x-motemen/ghq" = "latest"
bat = "latest"
deno = "latest"
gh = "latest"
"github:k1LoW/mo" = "latest"
"github:rokuosan/git-wtclean" = "v0.1.0"
go = "latest"
"go:github.com/fujimura/git-gsub" = "latest"
"go:github.com/k1LoW/git-wt" = "latest"
"go:github.com/rokuosan/qrg" = "v0.4.0"
java = "26.0.0"
lazygit = "latest"
node = "26.1.0"
"npm:@helpfeel/cosense-cli" = "latest"
usage = "latest"
viteplus = "latest"
watchexec = "latest"

[settings]
experimental = true

trusted_config_paths = ['~/repo/github.com/rokuosan']

minimum_release_age = "24h"
minimum_release_age_excludes = ["npm:@helpfeel/cosense-cli"]

[settings.github]
credential_command = "gh auth token --hostname github.com"
